-- TravelDashboard: create app_user and preference tables
-- Run this in Supabase SQL Editor or via Supabase MCP apply_migration / execute_sql

-- gen_random_uuid() lives in pgcrypto on Supabase.
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS app_user (
  user_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  first_name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS preference (
  preference_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES app_user(user_id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  dietary_restrictions TEXT,
  dining_preference TEXT
);

CREATE INDEX IF NOT EXISTS idx_preference_user_created_at
  ON preference (user_id, created_at DESC);

-- Optional: enable Row Level Security (RLS) and add policies if you later add auth.
-- ALTER TABLE app_user ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE preference ENABLE ROW LEVEL SECURITY;
