#!/usr/bin/env python3
"""Regenerate README.md from README.template.md + docs/architecture_v3.md (no Node required)."""

from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TEMPLATE = ROOT / "README.template.md"
ARCH = ROOT / "docs" / "architecture_v3.md"
OUT = ROOT / "README.md"
MARKER = "{{ARCHITECTURE_BODY}}"
BANNER = (
    "<!-- Generated by scripts/build_readme.py from README.template.md + docs/architecture_v3.md -->\n\n"
)


def normalize_architecture(md: str) -> str:
    trimmed = md.replace("\ufeff", "").strip("\n")
    lines = trimmed.split("\n")
    if lines and lines[0].startswith("# "):
        lines[0] = "### " + lines[0][2:]
    return "\n".join(lines).rstrip() + "\n"


def main() -> None:
    template = TEMPLATE.read_text(encoding="utf-8")
    if MARKER not in template:
        raise SystemExit(f"README.template.md must contain {MARKER}")
    arch = ARCH.read_text(encoding="utf-8")
    body = normalize_architecture(arch)
    OUT.write_text(BANNER + template.replace(MARKER, body), encoding="utf-8")
    print("Wrote README.md")


if __name__ == "__main__":
    main()
